package bt.an;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;

/**
 * Servlet implementation class AboutMe
 */
@WebServlet("/AboutMe")
public class AboutMe extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public AboutMe() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		response.setContentType("text/html");
		response.setCharacterEncoding("utf-8");
		PrintWriter print = response.getWriter();
		print.append(getHtml());
		
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
	}
	
	private String getHtml() {
		String print = "<html>\r\n"
				+ "<head>\r\n"
				+ "<meta charset=\"UTF-8\">\r\n"
				+ "<title>About Me</title>\r\n"
				+ "<link rel='stylesheet' href='style.css'>\r\n"
				+ "<link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>\r\n"
				+ "<style>"
				+ addCSS()
				+ "</style>"
				+ "</head>\r\n"
				+ "<body>\r\n"
				+ "	<header class='header'>\r\n"
				+ "		<a href='#' class='logo'>\r\n"
				+ "			Hoàng Duy\r\n"
				+ "			<span>An</span>\r\n"
				+ "		</a>\r\n"
				+ "		<nav class='navbar'>\r\n"
				+ "            <a href='#home' id='active'>Home</a>\r\n"
				+ "            <a href='#education'>Education</a>\r\n"
				+ "            <a href='#services'>Services</a>\r\n"
				+ "            <a href='#contact'>Contact</a>\r\n"
				+ "        </nav>\r\n"
				+ "	</header>\r\n"
				+ "	<section class='home' id='home'>\r\n"
				+ "        <div class='home-content'>\r\n"
				+ "            <h1>Hi, It's <span>An</span></h1>\r\n"
				+ "            <h3 class='text-animation'>I'm an <span>IT Student</span></h3>\r\n"
				+ "            <p>I'm studying at Information Technology falcuty in Nha Trang University. \r\n"
				+ "            I aim to be a frontend developer in the future. I'm passionate about\r\n"
				+ "            frontend technologies and love creating beautiful and functional user \r\n"
				+ "            interfaces. I am constantly learning and improving my skills to stay \r\n"
				+ "            updated with the latest trends in web development. I am looking for opportunities \r\n"
				+ "            to work on exciting projects and collaborate with other talented developers. \r\n"
				+ "            </p>\r\n"
				+ "\r\n"
				+ "            <div class='social-icons'>\r\n"
				+ "                <a href='#'><i class='bx bxl-linkedin' ></i></a>\r\n"
				+ "                <a href='#'><i class='bx bxl-github' ></i></a>\r\n"
				+ "                <a href='#'><i class='bx bxl-instagram-alt'></i></a>\r\n"
				+ "                <a href='#'><i class='bx bxl-facebook-circle'></i></a>\r\n"
				+ "            </div>\r\n"
				+ "\r\n"
				+ "            <div class='btn-group'>\r\n"
				+ "                <a href='#' class='btn'>More</a>\r\n"
				+ "                <a href='#contact' class='btn'>Contact</a>\r\n"
				+ "            </div>\r\n"
				+ "        </div>\r\n"
				+ "        <div class='home-img'>\r\n"
				+ "            <img src='duyan.jpg' alt=''>\r\n"
				+ "        </div>\r\n"
				+ "    </section>\r\n"
				+ "</body>\r\n"
				+ "</html>";
		return print;
	}
	
	private String addCSS() {
		String print = "*{\r\n"
				+ "    margin: 0;\r\n"
				+ "    padding: 0;\r\n"
				+ "    box-sizing: border-box;\r\n"
				+ "    text-decoration: none;\r\n"
				+ "    outline: none;\r\n"
				+ "    scroll-behavior: smooth;\r\n"
				+ "    font-family: 'Poppins', sans-serif;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ":root{\r\n"
				+ "    --bg-color: #fdfdfd;\r\n"
				+ "    --second-bg-color: #131313;\r\n"
				+ "    --text-color: black;\r\n"
				+ "    --main-color: rgb(16, 146, 188);\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "html{\r\n"
				+ "    font-size: 60%;\r\n"
				+ "    overflow-x: hidden;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "body{\r\n"
				+ "    background-color: var(--bg-color);\r\n"
				+ "    color: var(--text-color);\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".header{\r\n"
				+ "    position: fixed;\r\n"
				+ "    top: 0;\r\n"
				+ "    left: 0;\r\n"
				+ "    width: 100%;\r\n"
				+ "    padding: 4rem 12% 4rem;\r\n"
				+ "    background-color: rgb(253, 253, 253);\r\n"
				+ "    backdrop-filter: blur(10px);\r\n"
				+ "    display: flex;\r\n"
				+ "    justify-content: space-between;\r\n"
				+ "    align-items: center;\r\n"
				+ "    z-index: 5;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".logo{\r\n"
				+ "    font-size: 3rem;\r\n"
				+ "    color: var(--text-color);\r\n"
				+ "    font-weight: 800;\r\n"
				+ "    cursor: pointer;\r\n"
				+ "    transition: 0.3s ease\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".logo:hover{\r\n"
				+ "    transform: scale(1.1);\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".logo span{\r\n"
				+ "    text-shadow: 0 0 25px var(--main-color);\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".navbar a{\r\n"
				+ "    font-size: 1.8rem;\r\n"
				+ "    color: var(--text-color);\r\n"
				+ "    margin-left: 4rem;\r\n"
				+ "    font-weight: 500;\r\n"
				+ "    transition: 0.3s ease;\r\n"
				+ "    border-bottom: 3px solid transparent;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".navbar a:hover,\r\n"
				+ ".navbar a.active{\r\n"
				+ "    color: var(--main-color);\r\n"
				+ "    border-bottom: 3px solid var(--main-color);\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "#menu-icon{\r\n"
				+ "    font-size: 3.6rem;\r\n"
				+ "    color: var(--main-color);\r\n"
				+ "    display: none;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "section{\r\n"
				+ "    min-height: 100vh;\r\n"
				+ "    padding: 10rem 12% 10rem;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".home{\r\n"
				+ "    display: flex;\r\n"
				+ "    justify-content: center;\r\n"
				+ "    align-items: center;\r\n"
				+ "    gap: 15rem;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".home-content{\r\n"
				+ "    display: flex;\r\n"
				+ "    flex-direction: column;\r\n"
				+ "    align-items: baseline;\r\n"
				+ "    text-align: left;\r\n"
				+ "    justify-content: center;\r\n"
				+ "    margin-top: 3rem;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "span{\r\n"
				+ "    color: var(--main-color);\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".logo span{\r\n"
				+ "    color: var(--main-color);\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".home-content h3{\r\n"
				+ "    margin-bottom: 2rem;\r\n"
				+ "    margin-top: 1rem;\r\n"
				+ "    font-size: 3.5rem;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".home-content h1{\r\n"
				+ "    font-size: 7rem;\r\n"
				+ "    font-weight: 700;\r\n"
				+ "    margin-top: 1.5rem;\r\n"
				+ "    line-height: 1;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".home-content p{\r\n"
				+ "    font-size: 1.5rem;\r\n"
				+ "    text-align: justify;\r\n"
				+ "    font-weight: 500;\r\n"
				+ "    line-height: 1.8;\r\n"
				+ "    max-width: 1000px;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".home-img{\r\n"
				+ "    border-radius: 50%;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".home-img img{\r\n"
				+ "    position: relative;\r\n"
				+ "    top: 3rem;\r\n"
				+ "    width: 25vw;\r\n"
				+ "    border-radius: 50%;\r\n"
				+ "    box-shadow: 0 0 25px var(--main-color);\r\n"
				+ "    cursor: pointer;\r\n"
				+ "    transition: 0.4s ease-in-out;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".home-img img:hover{\r\n"
				+ "    box-shadow: 0 0 25px var(--main-color),\r\n"
				+ "                0 0 50px var(--main-color),\r\n"
				+ "                0 0 100px var(--main-color);\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "\r\n"
				+ ".social-icons a{\r\n"
				+ "    display: inline-flex;\r\n"
				+ "    justify-content: center;\r\n"
				+ "    align-items: center;\r\n"
				+ "    width: 4.5rem;\r\n"
				+ "    height: 4.5rem;\r\n"
				+ "    background: transparent;\r\n"
				+ "    border: 2px solid var(--main-color);\r\n"
				+ "    font-size: 2.5rem;\r\n"
				+ "    border-radius: 50%;\r\n"
				+ "    color: var(--main-color);\r\n"
				+ "    margin: 3rem 1.5rem 3rem 0;\r\n"
				+ "    transition: 0.3s ease-in-out;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".social-icons a:hover{\r\n"
				+ "    color: var(--text-color);\r\n"
				+ "    transform: scale(1.3)translateY(-5px);\r\n"
				+ "    box-shadow: 0 0 25px var(--main-color);\r\n"
				+ "    background-color: var(--main-color);\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".btn{\r\n"
				+ "    display: inline-block;\r\n"
				+ "    padding: 1rem 2.8rem;\r\n"
				+ "    background: var(--main-color);\r\n"
				+ "    box-shadow: 0 0 25px var(--main-color);\r\n"
				+ "    border-radius: 4rem;\r\n"
				+ "    font-size: 1.6rem;\r\n"
				+ "    color: white;\r\n"
				+ "    border: 2px solid transparent;\r\n"
				+ "    letter-spacing: 0.1rem;\r\n"
				+ "    font-weight: 600;\r\n"
				+ "    transition: 0.3s ease-in-out;\r\n"
				+ "    cursor: pointer;\r\n"
				+ "}	\r\n"
				+ "\r\n"
				+ ".btn:hover{\r\n"
				+ "    transform: scale(1.05);\r\n"
				+ "    align-items: center;\r\n"
				+ "    gap: 1.5rem;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".btn-group{\r\n"
				+ "    display: flex;\r\n"
				+ "    align-items: center;\r\n"
				+ "    gap: 1.5rem;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".btn-group a:nth-of-type(2){\r\n"
				+ "    background-color: white;\r\n"
				+ "    color: var(--main-color);\r\n"
				+ "    border: 2px solid var(--main-color);\r\n"
				+ "    box-shadow: 0 0 25px transparent;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".btn-group a:nth-of-type(2):hover{\r\n"
				+ "    box-shadow: 0 0 25px var(--main-color);\r\n"
				+ "    background-color: var(--main-color);\r\n"
				+ "    color: black;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".text-animation{\r\n"
				+ "    font-size: 34px;\r\n"
				+ "    font-weight: 600;\r\n"
				+ "    min-width: 280px;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".text-animation span{\r\n"
				+ "    position: relative;\r\n"
				+ "}";
		return print;
	}
}
